// Removed 'use client' directive to allow 'metadata' export
import { ReactNode } from 'react';
import { ThemeProvider } from 'next-themes';
import Header from '@/components/layouts/Header';
import Footer from '@/components/layouts/Footer';
import './globals.css';

export const metadata = {
  title: {
    default: 'Smart Finance Blog – Investing, Saving & Money Tips',
    template: '%s | Smart Finance Blog',
  },
  description:
    'Learn smart money management, investing strategies, and saving tips from experts. Achieve financial freedom with actionable guides and tools.',
  keywords: [
    'financial freedom',
    'investing tips',
    'saving money',
    'personal finance',
    'money management',
    'stock market',
    'ETFs',
    'budgeting',
  ],
  openGraph: {
    title: 'Smart Finance Blog – Investing, Saving & Money Tips',
    description:
      'Your go-to resource for smart money management, investing strategies, and saving tips to build wealth in 2025 and beyond.',
    url: 'https://your-finance-blog.com',
    siteName: 'Smart Finance Blog',
    images: [
      {
        url: 'https://images.unsplash.com/photo-1565372918675-3a04e54c05c5',
        width: 1200,
        height: 630,
        alt: 'Smart Finance Blog Cover',
      },
    ],
    locale: 'en_US',
    type: 'website',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Smart Finance Blog – Investing, Saving & Money Tips',
    description:
      'Smart money management, investing, and saving tips from experts. Build wealth in 2025.',
    images: ['https://images.unsplash.com/photo-1565372918675-3a04e54c05c5'],
  },
  alternates: {
    canonical: 'https://your-finance-blog.com',
  },
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta name="robots" content="index, follow, max-snippet:-1, max-image-preview:large, max-video-preview:-1" />
        <meta name="google-site-verification" content="your-google-verification-code" />
        <meta name="author" content="Your Name or Finance Expert" />
        <link rel="icon" href="/favicon.ico" />

        {/* JSON-LD Structured Data for Finance Blog */}
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              "@context": "https://schema.org",
              "@type": "Blog",
              name: "Smart Finance Blog",
              url: "https://your-finance-blog.com",
              description:
                "Smart finance tips, investing strategies, and money management guides for achieving financial freedom.",
              publisher: {
                "@type": "Organization",
                name: "Smart Finance Blog",
                logo: {
                  "@type": "ImageObject",
                  url: "https://your-finance-blog.com/logo.png",
                },
              },
              author: {
                "@type": "Person",
                name: "Your Name",
                url: "https://your-finance-blog.com/about",
              },
              mainEntityOfPage: {
                "@type": "WebPage",
                "@id": "https://your-finance-blog.com",
              },
            }),
          }}
        />
      </head>
      <body className="bg-secondary dark:bg-secondary-dark min-h-screen flex flex-col">
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <Header />
          <main className="flex-grow container mx-auto px-4 sm:px-6 lg:px-8 py-8">
            {children}
          </main>
          <Footer />
        </ThemeProvider>

        {/* Google Analytics */}
        <script
          async
          src={`https://www.googletagmanager.com/gtag/js?id=${process.env.NEXT_PUBLIC_GA_ID}`}
        ></script>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              window.dataLayer = window.dataLayer || [];
              function gtag(){dataLayer.push(arguments);}
              gtag('js', new Date());
              gtag('config', '${process.env.NEXT_PUBLIC_GA_ID}');
            `,
          }}
        />

        {/* Google AdSense */}
        <script
          async
          src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"
        ></script>

        {/* Popup Attribution */}
        <div id="root">
          <script
            dangerouslySetInnerHTML={{
              __html: `
                (function() {
                  const popup = document.createElement("div");
                  popup.innerHTML = "Generated by <strong>GenZai.in</strong>";
                  Object.assign(popup.style, {
                    position: "fixed",
                    bottom: "20px",
                    left: "20px",
                    backgroundColor: "rgba(0, 0, 0, 0.7)",
                    color: "#fff",
                    padding: "8px 12px",
                    borderRadius: "8px",
                    fontSize: "14px",
                    zIndex: "1000",
                    boxShadow: "0 4px 8px rgba(0, 0, 0, 0.2)",
                    opacity: "0",
                    transform: "translateY(10px)",
                    transition: "opacity 0.5s ease, transform 0.5s ease"
                  });
                  document.body.appendChild(popup);
                  requestAnimationFrame(() => {
                    popup.style.opacity = "1";
                    popup.style.transform = "translateY(0)";
                  });
                  setTimeout(() => {
                    popup.style.opacity = "0";
                    popup.style.transform = "translateY(10px)";
                    setTimeout(() => popup.remove(), 500);
                  }, 5000);
                })();
              `,
            }}
          />
        </div>
      </body>
    </html>
  );
}
